version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu

hooks:
  BeforeInstall:
    - location: scripts/set-permissions.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu